import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

public class GameSetup {

    private HashMap<String,Territory> world_map;
    private String territory_CSV;
    private ArrayList<Territory> unclaimed_territory;

    /**
     * GameSetup is in charge of calling private methods which
     * distribute the troops to players and then begins to place
     * the troops randomly on the world_map
     * @param players a list of the players, provided by Game object
     */
    public GameSetup(ArrayList<Player> players){
        this.territory_CSV = "TerritoryNeighbours.csv";
        this.world_map = new HashMap<>();
        this.unclaimed_territory = new ArrayList<>();
        set_neighbours(read_csv());
        distribute_troops(players);
        }

    /**
     * By the rules of risk you can have 3-6 players, when there are 3 players
     * each player starts with 35 troops, this value lowers by five for each
     * player new player.
     * @param players an array list of players
     */
    private void provide_troops(ArrayList<Player> players) {
        int distribute_val = 100 - 5 * (players.size() - 3);
        for (Player x : players) {
            x.add_troops(distribute_val);
        }
    }
    private void distribute_troops(ArrayList<Player> players){
        provide_troops(players);
        Random number_generator = new Random();
        Player current_player;
        Territory current_territory;
        int troop_num;
        for(int i = 0; unclaimed_territory.size() != 0;i++){
            current_player = players.get(i%players.size());
            current_territory =select_random_territory(unclaimed_territory);
            current_territory.setPlayer(current_player,current_player.place_troop(1));
            current_player.add_territory(current_territory);
            unclaimed_territory.remove(current_territory);
        }
        Territory random_territory;
        ArrayList<Territory> territory_list;
        int spread_factor = 4;
        for(Player curr_player : players){
            territory_list = new ArrayList<Territory>(curr_player.getTerritories_occupied().values());
            while(curr_player.getTroop_count_dist() != 0){
                troop_num = 1;
                random_territory = select_random_territory(territory_list);
                System.out.println("Terri: " + random_territory.getName());
                System.out.println("Player: " + random_territory.getPlayerString());
                System.out.println("Troop Count: " + troop_num);
                System.out.println("=============================================");
                random_territory.setTroops(curr_player.place_troop(troop_num));
            }
        }
        printWorldInfo();
    }
    private Territory select_random_territory(ArrayList<Territory> list_of_territories){
        Random number_generator = new Random();
        int territory_num;
        territory_num = number_generator.nextInt(list_of_territories.size()) ;
        return list_of_territories.get(territory_num);
    }
    /**
     * Iterate through ArrayList generated by CSV to obtain neighbours for
     * territories.
     * @param territories ArrayList generated from TerritoryNeighbours.csv
     */
    private void set_neighbours(ArrayList<String[]> territories){
        String continent_name = "";
        String territory_name = "";
        for(String[] temp_territory : territories){
            continent_name = temp_territory[0];
            territory_name = temp_territory[1];
            world_map.put(territory_name,new Territory(continent_name,territory_name));
        }
        for(String[] temp_territory : territories){
            territory_name = temp_territory[1];
            ArrayList<String> temp_sub = new ArrayList<String>(Arrays.asList(temp_territory));
            for(String temp_neighbours : temp_sub.subList(2,temp_sub.size())){
                world_map.get(territory_name).set_neighbour(temp_neighbours, world_map.get(temp_neighbours));
            }
        }
        unclaimed_territory.addAll(world_map.values());

    }

    /**
     * Read the CSV file and obtain the Neighbours
     * @return
     */
    private ArrayList<String[]> read_csv(){
        String row = "";
        ArrayList<String[]> territory_list = new ArrayList<>();

        try {
            BufferedReader reader = new BufferedReader(new FileReader(this.territory_CSV));
            reader.readLine(); //Skip first line
            while((row = reader.readLine()) != null){
                String[] territories = row.split(",");
                territory_list.add(territories);
            }
        } catch (FileNotFoundException e){
            System.out.println("Error: File not found");
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return territory_list;

    }
    public void printWorldInfo(){
        for(Territory x : world_map.values()){
            x.print_info();
        }
    }
    public HashMap<String,Territory> returnWorldMap(){
        return world_map;
    }
}

